### ISSUE TITLE
Error on make: Unknown cursor kind

### ISSUE THREAD

**Issue by abhi1010** [jlopezvi/Flowgen#5]
I am getting the following error running `make flowdoc`. Any ideas?

```bash
> make flowdoc
cpp-to-flowdb: preprocessing
python3 ../build_db.py simple_demo_src.cpp -I./include -I/opt/clang39/lib64/clang/3.9.1/include/
Translation unit: simple_demo_src.cpp
Traceback (most recent call last):
  File "../build_db.py", line 137, in <module>
    find_functions(tu.cursor)
  File "../build_db.py", line 118, in find_functions
    find_functions(c)
  File "../build_db.py", line 118, in find_functions
    find_functions(c)
  File "../build_db.py", line 97, in find_functions
    if node.kind.is_declaration():
  File "~/Flowgen/clang/cindex.py", line 1111, in kind
    return CursorKind.from_id(self._kind_id)
  File "~/Flowgen/clang/cindex.py", line 511, in from_id
    raise ValueError('Unknown cursor kind')
ValueError: Unknown cursor kind
Makefile:38: recipe for target 'flowdoc/aux_files/source1.flowdb' failed
```

**Comment by jlopezvi** [comment]
Hello,

Could you please indicate the system where you are running ? (Windows / Mac)
Have you followed the instructions at README.txt?
Thank you.

**Comment by carismoses** [comment]
@abhi1010 I believe I solved the issue you are having. I had the same one. During the `make flowdoc` prosses, /Flowgen/clang/cindex.py was looking for CursorKind = 417 and 603 which were missing from the enumeration at the bottom of the file. I found them at [](https://llvm.org/svn/llvm-project/cfe/trunk/bindings/python/clang/cindex.py). So if you add

```
CursorKind.VISIBILITY_ATTR = CursorKind(417)
CursorKind.FRIEND_DECL = CursorKind(603)
```

to your /Flowgen/clang/cindex.py you should be all set. I had some other issues with the make process as well but was able to get it to wark so let meknow if you run into any other issues!

**Comment by jlopezvi** [comment]
Thank you @carismoses.
If you do a pull request with the changes I will be happy to accept.

**Comment by deepsett** [comment]
Hi!

I am facing a similar issue. Here is a log of the output with some additional print statements included about the Cursor object
```
> make flowdoc
type <clang.cindex.Type object at 0x7fbaf84d5440>
displayname b''
location <SourceLocation file b'/usr/include/pthread.h', line 507, column 42>
Traceback (most recent call last):
  File "../build_db.py", line 141, in <module>
    find_functions(tu.cursor)
  File "../build_db.py", line 123, in find_functions
    find_functions(c)
  File "../build_db.py", line 123, in find_functions
    find_functions(c)
  File "../build_db.py", line 120, in find_functions
    print ('spelling', c.spelling)
  File "/home/ddsett/Hacklab/Flowgen/clang/cindex.py", line 1120, in spelling
    if not self.kind.is_declaration():
  File "/home/ddsett/Hacklab/Flowgen/clang/cindex.py", line 1115, in kind
    return CursorKind.from_id(self._kind_id)
  File "/home/ddsett/Hacklab/Flowgen/clang/cindex.py", line 511, in from_id
    raise ValueError('Unknown cursor kind')
ValueError: Unknown cursor kind
make: *** [Makefile:39: flowdoc/aux_files/source1.flowdb] Error 1`

```
Can anyone please help me resolve the issue?
